### ISSUE TITLE
Create test which validates GORM entity Constraints

### ISSUE THREAD

**Issue by sdelamo** [grails-samples/onezeroone#1]
[CourseSubscriberGormEntity](https://github.com/grails-samples/onezeroone/blob/master/app/grails-app/domain/org/grails/onezeroone/repository/gorm/CourseSubscriberGormEntity.groovy). See: http://guides.grails.org/grails-test-domain-class-constraints/guide/index.html

**Comment by ilopmar** [comment]
Fixed in #5
