### ISSUE TITLE
Implement GmailService

### ISSUE THREAD

**Issue by sdelamo** [grails-samples/onezeroone#3]
See: https://github.com/grails-samples/onezeroone/blob/master/app/grails-app/services/org/grails/onezeroone/plugins/gmail/GmailService.groovy

See branch email of grails-slack project for an example. 

https://github.com/grails-samples/grails-slack/tree/email

https://github.com/grails-samples/grails-slack/commit/dda13dac956ecacdce5d7d4292e0b3b298a4be1b

You could use plugin 

    compile 'org.grails.plugins:mail:2.0.0.RC6'

**Comment by ilopmar** [comment]
Closed via #7
